export const keyMetadata = {
  "0": { label: "0", apperance: "normal" },
  "1": { label: "1", apperance: "normal" },
  "2": { label: "2", apperance: "normal" },
  "3": { label: "3", apperance: "normal" },
  "4": { label: "4", apperance: "normal" },
  "5": { label: "5", apperance: "normal" },
  "6": { label: "6", apperance: "normal" },
  "7": { label: "7", apperance: "normal" },
  "8": { label: "8", apperance: "normal" },
  "9": { label: "9", apperance: "normal" },
  f13: { label: "F13", apperance: "normal" },
  f14: { label: "F14", apperance: "normal" },
  f15: { label: "F15", apperance: "normal" },
  f16: { label: "F16", apperance: "normal" },
  f17: { label: "F17", apperance: "normal" },
  f18: { label: "F18", apperance: "normal" },
  f19: { label: "F19", apperance: "normal" },
  f20: { label: "F20", apperance: "normal" },
  f21: { label: "F21", apperance: "normal" },
  f22: { label: "F22", apperance: "normal" },
  f23: { label: "F23", apperance: "normal" },
  f24: { label: "F24", apperance: "normal" },
  lwin: { label: "Left Super", apperance: "modifier" },
  ralt: { label: "Right alt", apperance: "modifier" },
  insert: { label: "Insert", apperance: "normal" },
  shutdn: { label: "Shutdown", apperance: "normal" },
  null: { label: "No Key Action", apperance: "normal" },
  kptoggle: { label: "Toggle Keypad", apperance: "layer" },
  kpshift: { label: "Shift Keypad", apperance: "layer" },
  "kp=mac": { label: "Keypad = (MAC)", apperance: "normal" },
  escape: { label: "Escape", apperance: "normal" },
  f1: { label: "F1", apperance: "normal" },
  f2: { label: "F2", apperance: "normal" },
  f3: { label: "F3", apperance: "normal" },
  f4: { label: "F4", apperance: "normal" },
  f5: { label: "F5", apperance: "normal" },
  f6: { label: "F6", apperance: "normal" },
  f7: { label: "F7", apperance: "normal" },
  f8: { label: "F8", apperance: "normal" },
  f9: { label: "F9", apperance: "normal" },
  f10: { label: "F10", apperance: "normal" },
  f11: { label: "F11", apperance: "normal" },
  f12: { label: "F12", apperance: "normal" },
  prtscr: { label: "Print Screen", apperance: "normal" },
  scroll: { label: "Scroll Lock", apperance: "normal" },
  pause: { label: "Pause / Break", apperance: "normal" },
  keypd: { label: "Keypad toggle", apperance: "layer" },
  progrm: { label: "Program", apperance: "layer" },
  "=": { label: "=", apperance: "normal" },
  hyphen: { label: "-", apperance: "normal" },
  tab: { label: "Tab", apperance: "normal" },
  q: { label: "Q", apperance: "normal" },
  w: { label: "W", apperance: "normal" },
  e: { label: "E", apperance: "normal" },
  r: { label: "R", apperance: "normal" },
  t: { label: "T", apperance: "normal" },
  y: { label: "Y", apperance: "normal" },
  u: { label: "U", apperance: "normal" },
  i: { label: "I", apperance: "normal" },
  o: { label: "O", apperance: "normal" },
  p: { label: "P", apperance: "normal" },
  "\\": { label: "\\", apperance: "normal" },
  caps: { label: "Caps Lock", apperance: "normal" },
  a: { label: "A", apperance: "normal" },
  s: { label: "S", apperance: "normal" },
  d: { label: "D", apperance: "normal" },
  f: { label: "F", apperance: "normal" },
  g: { label: "G", apperance: "normal" },
  h: { label: "H", apperance: "normal" },
  j: { label: "J", apperance: "normal" },
  k: { label: "K", apperance: "normal" },
  l: { label: "L", apperance: "normal" },
  ";": { label: ";", apperance: "normal" },
  "'": { label: `'`, apperance: "normal" },
  lshift: { label: "Left shift", apperance: "modifier" },
  z: { label: "Z", apperance: "normal" },
  x: { label: "X", apperance: "normal" },
  c: { label: "C", apperance: "normal" },
  v: { label: "V", apperance: "normal" },
  b: { label: "B", apperance: "normal" },
  n: { label: "N", apperance: "normal" },
  m: { label: "M", apperance: "normal" },
  ",": { label: ",", apperance: "normal" },
  ".": { label: ".", apperance: "normal" },
  "/": { label: "/", apperance: "normal" },
  rshift: { label: "Right shift", apperance: "modifier" },
  "`": { label: "`", apperance: "normal" },
  "intl-\\": { label: "International Key", apperance: "normal" },
  left: { label: "Left", apperance: "normal" },
  right: { label: "Right", apperance: "normal" },
  up: { label: "Up", apperance: "normal" },
  down: { label: "Down", apperance: "normal" },
  obrack: { label: "[", apperance: "normal" },
  cbrack: { label: "]", apperance: "normal" },
  lctrl: { label: "Left control", apperance: "modifier" },
  lalt: { label: "Left alt", apperance: "modifier" },
  rwin: { label: "Right Super", apperance: "modifier" },
  rctrl: { label: "Right control", apperance: "modifier" },
  bspace: { label: "Backspace", apperance: "normal" },
  delete: { label: "Delete", apperance: "normal" },
  home: { label: "Home", apperance: "normal" },
  pup: { label: "Page Up", apperance: "normal" },
  enter: { label: "Enter", apperance: "normal" },
  space: { label: "Space", apperance: "normal" },
  end: { label: "End", apperance: "normal" },
  pdown: { label: "Page Down", apperance: "normal" },
  "kp-escape": { label: "Escape", apperance: "normal" },
  "kp-lwin": { label: "Left Super", apperance: "modifier" },
  "kp-ralt": { label: "Right Alt", apperance: "modifier" },
  "kp-rwin": { label: "Right Super", apperance: "modifier" },
  menu: { label: "Menu / App", apperance: "normal" },
  play: { label: "Play / Pause", apperance: "normal" },
  prev: { label: "Previous Track", apperance: "normal" },
  next: { label: "Next Track", apperance: "normal" },
  calc: { label: "Calculator", apperance: "normal" },
  "kp-f9": { label: "F9", apperance: "normal" },
  "kp-f10": { label: "F10", apperance: "normal" },
  "kp-f11": { label: "F11", apperance: "normal" },
  "kp-f12": { label: "F12", apperance: "normal" },
  mute: { label: "Mute", apperance: "normal" },
  "vol-": { label: "Volume Down", apperance: "normal" },
  "vol+": { label: "Volumne Up", apperance: "normal" },
  "kp-=": { label: "=", apperance: "normal" },
  "kp-1": { label: "1", apperance: "normal" },
  "kp-2": { label: "2", apperance: "normal" },
  "kp-3": { label: "3", apperance: "normal" },
  "kp-4": { label: "4", apperance: "normal" },
  "kp-5": { label: "5", apperance: "normal" },
  "kp-6": { label: "6", apperance: "normal" },
  numlk: { label: "Num Lock", apperance: "normal" },
  "kp=": { label: "Keypad =", apperance: "normal" },
  kpdiv: { label: "Keypad /", apperance: "normal" },
  kpmult: { label: "Keypad *", apperance: "normal" },
  "kp-hyphen": { label: "-", apperance: "normal" },
  "kp-tab": { label: "Tab", apperance: "normal" },
  "kp-q": { label: "Q", apperance: "normal" },
  "kp-w": { label: "W", apperance: "normal" },
  "kp-e": { label: "E", apperance: "normal" },
  "kp-r": { label: "R", apperance: "normal" },
  "kp-t": { label: "T", apperance: "normal" },
  "kp-y": { label: "Y", apperance: "normal" },
  kp7: { label: "Keypad 7", apperance: "normal" },
  kp8: { label: "Keypad 8", apperance: "normal" },
  kp9: { label: "Keypad 9", apperance: "normal" },
  kpmin: { label: "Keypad -", apperance: "normal" },
  "kp-\\": { label: "\\", apperance: "normal" },
  "kp-caps": { label: "Caps Lock", apperance: "normal" },
  "kp-a": { label: "A", apperance: "normal" },
  "kp-s": { label: "S", apperance: "normal" },
  "kp-d": { label: "D", apperance: "normal" },
  "kp-f": { label: "F", apperance: "normal" },
  "kp-g": { label: "G", apperance: "normal" },
  "kp-h": { label: "H", apperance: "normal" },
  kp4: { label: "Keypad 4", apperance: "normal" },
  kp5: { label: "Keypad 5", apperance: "normal" },
  kp6: { label: "Keypad 6", apperance: "normal" },
  kpplus: { label: "Keypad +", apperance: "normal" },
  "kp-'": { label: `'`, apperance: "normal" },
  "kp-lshift": { label: "Left shift", apperance: "modifier" },
  "kp-z": { label: "Z", apperance: "normal" },
  "kp-x": { label: "X", apperance: "normal" },
  "kp-c": { label: "C", apperance: "normal" },
  "kp-v": { label: "V", apperance: "normal" },
  "kp-b": { label: "B", apperance: "normal" },
  "kp-n": { label: "N", apperance: "normal" },
  kp1: { label: "Keypad 1", apperance: "normal" },
  kp2: { label: "Keypad 2", apperance: "normal" },
  kp3: { label: "Keypad 3", apperance: "normal" },
  kpenter1: { label: "Keypad Enter", apperance: "normal" },
  "kp-rshift": { label: "Right shift", apperance: "modifier" },
  "kp-`": { label: "`", apperance: "normal" },
  "kp-insert": { label: "Insert", apperance: "normal" },
  "kp-left": { label: "Left", apperance: "normal" },
  "kp-right": { label: "Right", apperance: "normal" },
  "kp-up": { label: "Up", apperance: "normal" },
  "kp-down": { label: "Down", apperance: "normal" },
  "kp.": { label: "Keypad .", apperance: "normal" },
  kpenter2: { label: "Keypad Enter", apperance: "normal" },
  "kp-lctrl": { label: "Left control", apperance: "modifier" },
  "kp-alt": { label: "Left alt", apperance: "modifier" },
  "kp-rctrl": { label: "Right control", apperance: "modifier" },
  "kp-bspace": { label: "Backspace", apperance: "normal" },
  "kp-delete": { label: "Delete", apperance: "normal" },
  "kp-home": { label: "Home", apperance: "normal" },
  "kp-pup": { label: "Page Up", apperance: "normal" },
  "kp-enter": { label: "Enter", apperance: "normal" },
  kp0: { label: "Keypad 0", apperance: "normal" },
  "kp-end": { label: "End", apperance: "normal" },
  "kp-pdown": { label: "Page Down", apperance: "normal" },
  "hyper": { label: "Hyper", apperance: "modifier" },
  "meh": { label: "Meh", apperance: "modifier" },
  "lmouse": { label: "Left mouse", apperance: "normal" },
  "rmouse": { label: "Right mouse", apperance: "normal" },
  "mmouse": { label: "Middle mouse", apperance: "normal" },
};

export type KeyToken = keyof typeof keyMetadata;
export type KeyboardLayer = {
  fn: KeyToken[];
  main: KeyToken[];
  thumb: KeyToken[];
};
export type Keymap = { top: KeyboardLayer; keypad: KeyboardLayer };
export type Remap = Partial<Record<KeyToken, KeyToken>>;

export const defaultKeymap: Keymap = {
  top: {
    fn: [
      "escape",
      "f1",
      "f2",
      "f3",
      "f4",
      "f5",
      "f6",
      "f7",
      "f8",
      "f9",
      "f10",
      "f11",
      "f12",
      "prtscr",
      "scroll",
      "pause",
      "keypd",
      "progrm",
    ],
    main: [
      "=",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "0",
      "hyphen",
      "tab",
      "q",
      "w",
      "e",
      "r",
      "t",
      "y",
      "u",
      "i",
      "o",
      "p",
      "\\",
      "caps",
      "a",
      "s",
      "d",
      "f",
      "g",
      "h",
      "j",
      "k",
      "l",
      ";",
      "'",
      "lshift",
      "z",
      "x",
      "c",
      "v",
      "b",
      "n",
      "m",
      ",",
      ".",
      "/",
      "rshift",
      "`",
      "intl-\\",
      "left",
      "right",
      "up",
      "down",
      "obrack",
      "cbrack",
    ],
    thumb: [
      "lctrl",
      "lalt",
      "rwin",
      "rctrl",
      "bspace",
      "delete",
      "home",
      "pup",
      "enter",
      "space",
      "end",
      "pdown",
    ],
  },
  keypad: {
    fn: [
      "kp-escape",
      "kp-lwin",
      "kp-ralt",
      "menu",
      "play",
      "prev",
      "next",
      "calc",
      "kpshift",
      "kp-f9",
      "kp-f10",
      "kp-f11",
      "kp-f12",
      "mute",
      "vol-",
      "vol+",
      "keypd",
      "progrm",
    ],
    main: [
      "kp-=",
      "kp-1",
      "kp-2",
      "kp-3",
      "kp-4",
      "kp-5",
      "kp-6",
      "numlk",
      "kp=",
      "kpdiv",
      "kpmult",
      "kp-hyphen",
      "kp-tab",
      "kp-q",
      "kp-w",
      "kp-e",
      "kp-r",
      "kp-t",
      "kp-y",
      "kp7",
      "kp8",
      "kp9",
      "kpmin",
      "kp-\\",
      "kp-caps",
      "kp-a",
      "kp-s",
      "kp-d",
      "kp-f",
      "kp-g",
      "kp-h",
      "kp4",
      "kp5",
      "kp6",
      "kpplus",
      "kp-'",
      "kp-lshift",
      "kp-z",
      "kp-x",
      "kp-c",
      "kp-v",
      "kp-b",
      "kp-n",
      "kp1",
      "kp2",
      "kp3",
      "kpenter1",
      "kp-rshift",
      "kp-`",
      "kp-insert",
      "kp-left",
      "kp-right",
      "kp-up",
      "kp-down",
      "kp.",
      "kpenter2",
    ],
    thumb: [
      "kp-lctrl",
      "kp-alt",
      "kp-rwin",
      "kp-rctrl",
      "kp-bspace",
      "kp-delete",
      "kp-home",
      "kp-pup",
      "kp-enter",
      "kp0",
      "kp-end",
      "kp-pdown",
    ],
  },
};
